plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE-hyde.md
  - deploy.sh
  - IDEAS.md

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Style
sass:
  style: compressed

# Setup
title:            dojo7
url:              https://dojo7.com
baseurl:          /

paginate:         3

google_analytics: "UA-611756-6"

github:           "https://github.com/captainpete"
linkedin:         "https://www.linkedin.com/in/peterhollows/"
stack_exchange:   "https://stackexchange.com/users/128088/captainpete"
keybase:          "https://keybase.io/captainpete"
twitter:          "https://twitter.com/_captainpete"
email:            "mailto:contact@dojo7.com"

