# SITE CONFIGURATION
baseurl: ""
url: "https://dojo7.com"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: dojo7
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: 5c155cc002e71bd399673df657e2c1bf # Email MD5 hash
  description: "Journal of experiments in machine learning, reinforcement learning and meta-learning."

  # Icons
  rss: false
  email_address: www@dojo7.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "captainpete"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/peterhollows/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: "https://stackexchange.com/users/128088/captainpete" # Full URL
  steam:
  tumblr:
  twitter: "_captainpete"
  wordpress:
  youtube:
  keybase: "https://keybase.io/captainpete"

  # Scripts
  google_analytics: "UA-611756-6" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE-type-theme

